version: "3.3"
services:
    redis:
        image: 'redis:4.0.10-alpine'
        container_name: 'redis'
        ports:
            - '6379:6379'
        volumes: 
            - ./redis/cache-data:/data
        restart: always
    mongo:
        image: 'mongo'
        container_name: 'mongo-db'
        ports:
            - '27017-27019:27017-27019'
        volumes: 
            - ./mongo/db-data:/data/db
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports: 
            - '3001:3001'
        restart: on-failure
        container_name: backend
