version: "3.3"
services:
    redis:
        image: 'redis:4.0.10-alpine'
        container_name: 'redis'
        ports:
            - '6379:6379'
        volumes: 
            - ./redis/db-data:/data
        restart: always